name: untitled
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  typed_data: ^1.3.0
  win32: ^5.0.3  # جرب استخدام نسخة متوافقة


  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  get: ^4.6.5
  dartz: ^0.10.1
  get_storage: ^2.1.1
  http: ^0.13.6
  responsive_framework: 0.2.0
  connectivity_plus: ^5.0.2
  sqflite: ^2.2.8+4
flutter_screenutil: any

image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # Custom fonts section:
  fonts:
    - family: Raleway
      fonts:
          - asset: assets/fonts/Raleway-VariableFont_wght.ttf
          - asset: assets/fonts/Raleway-Bold.ttf
    - family: Poppins
      fonts:
          - asset: assets/fonts/Poppins-ExtraLight.ttf